FROM node:lts-alpine

copy ./app/package.json /app/package.json
WORKDIR /app
RUN npm install -g --registry=https://registry.npmmirror.com cnpm && cnpm install

copy ./app /app

CMD ["node", "main.js"]