FROM node:lts-alpine

COPY ./app/package.json /app/package.json
WORKDIR /app
RUN npm install -g --registry=https://registry.npmmirror.com cnpm && cnpm install

COPY ./app /app

CMD ["sh", "/app/docker_entrypoint.sh"]

EXPOSE 3000 3001